name: Python Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8]
      
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      
      - name: install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pytest
          pip install flake8-black==0.2.1
          if [ -f reqirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Unit Test
        run: |
          pytest -v tests
      
      - name: Code Style
        run: |
          flake8 . --select BLK --extend-exclude=dist,build --show-source --statistics


